const SWEEPER_ACTION_TYPES = {
  SEED_BOARD: "SEED_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  UNCOVER: "UNCOVER",
  GAME_OVER: "GAME_OVER",
  RIGHT_CLICK: "RIGHT_CLICK"
}

export default SWEEPER_ACTION_TYPES;