const SWEEPER_ACTION_TYPES = {
  SEED_BOARD: "SEED_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  UNCOVER: "UNCOVER",
  GAME_OVER: "GAME_OVER",
  RIGHT_CLICK: "RIGHT_CLICK",
  TOGGLE_PLAY: "TOGGLE_PLAY",
  TOGGLE_FLAG_MODE: "TOGGLE_FLAG_MODE"
}

export default SWEEPER_ACTION_TYPES;